services:
  reverse-proxy:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  web:
    build: .
    ports:
      - "8080:8080"
